---

- name: Deploy application
  hosts: servers
  become: yes


  vars:
    project_dir: /opt/my_app


  tasks:
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'


    - name: Copy docker-compose file\
      copy:
        src: docker-compose.yaml
        dest: "{{ project_dir }}/docker-compose.yaml"



    - name: Copy Nginx config
      copy:
        src: my_nginx.conf
        dest: "{{ project_dir }}/my_nginx.conf"


    - name: Copy Prometheus dir
      copy:
        src: prometheus
        dest: "{{ project_dir }}/"


    - name: Copy Certs dir
      copy:
        src: certs
        dest: "{{ project_dir }}/"



    - name: Start docker-compose
      shell: docker compose up -d
      args:
        chdir: "{{ project_dir }}"
